### ISSUE TITLE
Error including the addon

### ISSUE THREAD

**Issue by theavish** [panosvoudouris/storybook-addon-versions#1]
I've added `import '@panosvoudouris/addon-versions/register';` to my `addons.js`, and my storybook breaks with the following error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve './dist/register' in 'C:\Projects\<projectName>\node_modules\@panosvoudouris\
addon-versions'
```

Afaik, that's the standard method of including storybook addons, unless im missing something? I'm running `storybook/react@5.1.x`

**Comment by panosvoudouris** [comment]
I've not checked it with storybook 5 but it works ok with v4. If you look in node_modules can you see the package and the contents ok?

**Comment by panosvoudouris** [comment]
Oh just noticed you're using Windows. Can you try `import '@panosvoudouris/addon-versions/dist/register';` I'll have to check if there's anything different needed for windows.

**Comment by theavish** [comment]
![image](https://user-images.githubusercontent.com/8893033/59879983-90b6d700-9371-11e9-91fb-bb82ccfcc5f6.png)
this is all i have under `node_modules`, it seems like the library isn't including the dist directory at all. 🤔 

(thanks for the quick response!)

**Comment by panosvoudouris** [comment]
Weird, I just tried a clean install and everything is there. Also got the tgz from npm and that also has everything. Can you delete that directory and add again? Can't really think what else to do.

**Comment by theavish** [comment]
i'm taking the following steps:
1. delete `node_modules` and `package-lock.json`
1. remove dependency from `package.json`
1. run `npm i -D @panosvoudouris/addon-versions`

**Comment by theavish** [comment]
and it seems to work this time.... fresh installs do wonders i suppose 🤷‍♂

**Comment by panosvoudouris** [comment]
The wonders of npm!
