### ISSUE TITLE
No Versions Found

### ISSUE THREAD

**Issue by theavish** [panosvoudouris/storybook-addon-versions#3]
I'm getting a message saying `No Versions Found` in the addon panel. I have 2 versions in my `storybook-config.json`:
```
{
    "storybook": {
        "versions": {
            "availableVersions": [
                "1.1.1",
                "1.1.2"
            ],
            "hostname": "localhost:6006",
            "localhost": "localhost:6006",
            "regex": "\/([^\/]+?)\/?$"
        }
    }
}
```
Those storybook builds are located at `<projectRoot>/docs/<version>`, which i can confirm are present on disk. Any ideas?

**Comment by panosvoudouris** [comment]
Is that using the `start-storybook` script? You need to tell it where the file is using the `-s` parameter, eg `start-storybook -p 3000 -s .storybook`, this way it will know where the json config is.

**Comment by theavish** [comment]
adding the `-s` param gets the versions displayed in the panel now, but i'm getting a `Cannot GET /1.1.1/` error when i click the button

**Comment by panosvoudouris** [comment]
I've not tested it with version stored further down than root, like in your example which is /docs/1.2.3. So that probably requires some changes.

**Comment by theavish** [comment]
changing my static build command from 
```
build-storybook -c .storybook -o docs/%v
```
to
```
build-storybook -c .storybook -o %v
```

doesn't seem to change the error

**Comment by panosvoudouris** [comment]
So it doesn't matter where you build it, in the end you have to move the static build somewhere to serve it (or setup you web server accordingly). You do need a webserver for this to work (can't just do it opening local files) and the webserver needs to see this in the root:
```
/storybook-config.json
/1.1.1/<files from static storybook build>
/1.x.x/
```

So when in your browser you type localhost/1.1.1/ you see that version and in the panel you'll have the rest and then you can navigate.
